@url = http://localhost:8080/hike

GET {{url}} HTTP/1.1

###

GET {{url}}/2 HTTP/1.1

###

PUT {{url}}/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJidWctc2FmYXJpIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhcHBfdXNlcl9pZCI6MSwiYXV0aG9yaXRpZXMiOiJBRE1JTiIsImV4cCI6MTY3NDE2NTMwNn0.6KpCdLtEz-GN9iRXD05IMDWeK2s5WaNA6XwMAmPwxM4
Content-Type: application/json

{
    "hikeId": 1,
    "hikeDate": "2020-11-20",
    "hikeDifficulty": "Difficult",
    "description": "Test Update",
    "hikerId": 3,
    "trailId": 41
}

###

DELETE {{url}}/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJidWctc2FmYXJpIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhcHBfdXNlcl9pZCI6MSwiYXV0aG9yaXRpZXMiOiJBRE1JTiIsImV4cCI6MTY3NDE2NDI0OH0.yP6kgoy5Q6olMEQUzFs4wKtDTzsm7hbcwRa8TpN3Q9U

###
POST {{url}} HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJidWctc2FmYXJpIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhcHBfdXNlcl9pZCI6MSwiYXV0aG9yaXRpZXMiOiJBRE1JTiIsImV4cCI6MTY3NDE2NTY3OH0.-FeJ98yEJstNt7v0K59QN5jWs8F_EjdypE52uuVa3BE
Content-Type: application/json

{
    "hikeDate": "2021-10-31",
    "hikeDifficulty": "Easy",
    "description": "Great mountains!",
    "hikerId": 3,
    "trailId": 35
}