@url = http://localhost:8080/hiker

GET {{url}} HTTP/1.1

###

GET {{url}}/therealjohnsmith HTTP/1.1

 
###

PUT {{url}}/bigsleeper893 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJidWctc2FmYXJpIiwic3ViIjoidGhlcmVhbGpvaG5zbWl0aCIsImFwcF91c2VyX2lkIjoxLCJhdXRob3JpdGllcyI6IkFETUlOIiwiZXhwIjoxNjc0NjEzODUzfQ.LLKrfpMMnVTpeXLJ03leKr_YqKTKORTG2pN8oit20lU
Content-Type: application/json

{
    "hikerId": "bigsleeper893",
    "firstName": "Gerald",
    "lastName": "Jackson",
    "age":29

}

###

DELETE {{url}}/neverinfilm HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJidWctc2FmYXJpIiwic3ViIjoidGhlcmVhbGpvaG5zbWl0aCIsImFwcF91c2VyX2lkIjoxLCJhdXRob3JpdGllcyI6IkFETUlOIiwiZXhwIjoxNjc0NjEyOTAxfQ.HjKISARX7GIxecB1LMqcNEx3PJRbpHxM9x12tSz8h20

###

POST {{url}} HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJidWctc2FmYXJpIiwic3ViIjoidGhlcmVhbGpvaG5zbWl0aCIsImFwcF91c2VyX2lkIjoxLCJhdXRob3JpdGllcyI6IkFETUlOIiwiZXhwIjoxNjc0NjIwOTEwfQ.06p_YDxkKOrKaD8GP-YyJ0H12991zUWj6gsnIAh3lI8
Content-Type: application/json 

{
    "hikerId": "rachelFromFriends",
    "firstName": "Jennifer",
    "lastName": "Aniston",
    "age": 41

    // Need to add to app_user and app user role tables as well as hiker table
}


