@url = http://localhost:8080/hike

GET {{url}} HTTP/1.1

###

GET {{url}}/2 HTTP/1.1

###

PUT {{url}}/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJidWctc2FmYXJpIiwic3ViIjoidGhlcmVhbGpvaG5zbWl0aCIsImFwcF91c2VyX2lkIjoxLCJhdXRob3JpdGllcyI6IkFETUlOIiwiZXhwIjoxNjc0NjE0MDc3fQ.L2akYcit8qQlkScOl7xYoL72XUs3i-kKffAKnj7rzC0
Content-Type: application/json

{
    "hikeId": 1,
    "hikeDate": "2020-11-20",
    "hikeDifficulty": "Difficult",
    "description": "Test Update",
    "hikerId": "veryunf0rtunatevi",
    "trailId": 41
}

###

DELETE {{url}}/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJidWctc2FmYXJpIiwic3ViIjoidGhlcmVhbGpvaG5zbWl0aCIsImFwcF91c2VyX2lkIjoxLCJhdXRob3JpdGllcyI6IkFETUlOIiwiZXhwIjoxNjc0NjEyOTAxfQ.HjKISARX7GIxecB1LMqcNEx3PJRbpHxM9x12tSz8h20
###

POST {{url}} HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJidWctc2FmYXJpIiwic3ViIjoicmFjaGVsRnJvbUZyaWVuZHM1IiwiYXBwX3VzZXJfaWQiOjE0LCJhdXRob3JpdGllcyI6IlVTRVIiLCJleHAiOjE2NzQ2NjU1NjB9.mogcaqtqTad1nnXQ7x6ZFMYvNKP9Vg2FLidL2PEuQyU
Content-Type: application/json

{
    "hikeDate": "2021-11-09",
    "hikeDifficulty": "Intermediate",
    "description": "birds",
    "hikerId": "rachelFromFriends5",
    "trailId": 35
}