@url = http://localhost:8080/hiker

GET {{url}} HTTP/1.1

###

GET {{url}}/1 HTTP/1.1

 
###

PUT {{url}}/2 HTTP/1.1
Content-Type: application/json

{
    "hiker_id": 1,
    "first_name": "Percy",
    "last_name": "Jackson",
    "age":29,
    "email": "defenderOfTheOceans.demigod@aol.com"
}

###

DELETE {{url}}/2 HTTP/1.1
