@url = http://localhost:8080/hiker

GET {{url}} HTTP/1.1

###

GET {{url}}/1 HTTP/1.1

 
###

PUT {{url}}/2 HTTP/1.1
Content-Type: application/json

{
    "hikerId": 1,
    "firstName": "Percy",
    "lastName": "Jackson",
    "age":29,
    "email": "defenderOfTheOceans.demigod@aol.com"
}

###

DELETE {{url}}/2 HTTP/1.1

###

POST {{url}} HTTP/1.1
Authorization: Bearer
Content-Type: application/json

{
    "firstName": "Jennifer",
    "lastName": "Aniston",
    "age": 41,
    "email": "rachelFromFriends@gmail.com"
}
