@url = http://localhost:8080/hike

GET {{url}} HTTP/1.1

###

GET {{url}}/2 HTTP/1.1

###

PUT {{url}}/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJidWctc2FmYXJpIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhcHBfdXNlcl9pZCI6MSwiYXV0aG9yaXRpZXMiOiJBRE1JTiIsImV4cCI6MTY3NDI0MzI1M30.j63fTBkgv7xTjg3Lbh3ehhiygQ4JVmSaqXcDGc9fAMo
Content-Type: application/json

{
    "hikeId": 1,
    "hikeDate": "2020-11-20",
    "hikeDifficulty": "Difficult",
    "description": "Test Update",
    "hikerId": 3,
    "trailId": 41
}

###

DELETE {{url}}/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJidWctc2FmYXJpIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhcHBfdXNlcl9pZCI6MSwiYXV0aG9yaXRpZXMiOiJBRE1JTiIsImV4cCI6MTY3NDI0MzI1M30.j63fTBkgv7xTjg3Lbh3ehhiygQ4JVmSaqXcDGc9fAMo

###

POST {{url}} HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJidWctc2FmYXJpIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhcHBfdXNlcl9pZCI6MSwiYXV0aG9yaXRpZXMiOiJBRE1JTiIsImV4cCI6MTY3NDI0MzI1M30.j63fTBkgv7xTjg3Lbh3ehhiygQ4JVmSaqXcDGc9fAMo
Content-Type: application/json

{
    "hikeDate": "2021-10-31",
    "hikeDifficulty": "Easy",
    "description": "Great mountains!",
    "hikerId": 3,
    "trailId": 35
}